### PR TITLE
Feature/ewl 3927 containerize css

### PR DESCRIPTION
**Pull request by rpama**
## Ticket(s)

Please do not submit a Pull Request without a relevant ticket! If you are creating a new pattern or feature, create an issue describing the need for this feature Github **first** and then link to it below.

**Jira Ticket**

- [EWL-3927: SG | Containerize CSS](https://issues.ama-assn.org/browse/EWL-3927)

## Description
Adds an .ama-theme wrapper class and wraps a ton of our css with it so that this won't break Drupal tools. 

## To Test

- [ ] Review the entire styleguide for regressions except where noted in the ticket (seriously)
- [ ] probably test this in D8 too and make sure it's actually solving the problem of css bleedthrough

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks

- [EWL-3928: D8 | Containerize CSS](https://issues.ama-assn.org/browse/EWL-3928)

At some later point, probably everything will need to be wrapped but they are specific enough now to not cause regressions or interfere with the Drupal styles. This covers all the things that seemed to absolutely require it to get the proper styles in the hope that it will make QAing easier.

## Additional Notes

Anything more to add?

### CODE REVIEW

**Comment by froboy** [comment]
welcome_to_ama-d8___ama-d8
admin___ama-d8_
testing___ama-d8_
Everything looks good... I'm able to temporarily add the `ama-theme` class to the content and the content gets styled correctly and the IPE remains unstyled. 
testing___ama-d8_

**Comment by froboy** [comment]
bitmoji

**Comment by megansabina** [comment]
@chelsiejohnston @rpama  - Would you like me to review this one more time?

**Comment by rpama** [comment]
@megansabina @chelsiejohnston I would like _someone_ to review & merge. It doesn't matter who. Usually the primary reviewer finishes a review @megansabina but if you have good reason to want another set of eyes on it, it's in your prerogative to delegate.

**Pull request merged**
