### PR TITLE
EWL-3816 create assets branch

### PR DESCRIPTION
**Pull request by froboy**
## Ticket(s)

Please do not submit a Pull Request without a relevant ticket! If you are creating a new pattern or feature, create an issue describing the need for this feature Github **first** and then link to it below.

**Github Issue**

NA

**Jira Ticket**

- [EWL-3816: Topics | SG | How to see off-release SG work in Drupal](https://issues.ama-assn.org/browse/EWL-3816)

## Description

This adds an option to the deploy task (also the option to include other options) to push to a new `dev-assets` branch.

## To Test

- ~`npm install` to install the minimist library which allows gulp to easily digest CLI options~
- Check out README.md for instructions on how to push to the new branch.
- Try it out. 

## Relevant Screenshots/GIFs

After a successful push you should see something like so:
banners_and_alerts_and_styleguide_ _-bash_ _89x24

## Remaining Tasks

No

## Additional Notes

This relates to https://github.com/AmericanMedicalAssociation/ama-d8/pull/14

### CODE REVIEW

**Comment by froboy** [comment]
@rpama yea... I kinda got a little tool-happy with the flags. I wanted to not duplicate the task, but it is literally one line, so I guess that's prob safer. @deadarm @chelsiejohnston thoughts?

**Comment by rpama** [comment]
Don't get me wrong @froboy, it's cool that it's really flexible like that. I've just fat fingered the command line enough in my day to worry that we could spend a lot of time wondering why Drupal didn't have our style updates and it'll be because we pushed to `dev-asssets` or something.

**Comment by rpama** [comment]
I guess I wonder what advantage we gain from using a flag instead of a distinctly separate gulp command. If I get `--drupal` wrong, will it fail or will it deploy to the `gh-pages`?

I realize wanting to keep gulp tasks somewhat DRY is a good goal, but in this case I think it comes at the expense of clarity and usability on our end.

**Comment by froboy** [comment]
But... we'd get to add a new dependency if we add a flag and it's cool and stuff fine i'll take it out whatever.

**Comment by froboy** [comment]
@rpama I've changed the process based on your feedback. I was able to at least only make one new task instead of two by using a global to set the branch. Now if we need to deploy to another branch later we can set it in another task.

**Pull request merged**
