### PR TITLE
[EWL-3995] : the commit where I finally remember that floats are useful

### PR DESCRIPTION
**Pull request by rpama**
## Ticket(s)

**Jira Ticket**

- [EWL-3995: Topics | Create two-column layout on tablet](https://issues.ama-assn.org/browse/EWL-3995)

## Description

In this PR you will come to know the limitations of flexbox and why floats are still your friends.

## To Test

- [x] Go to the Topics Template
- [x] Resize the heck out of your screen
- [x] See the glorious two-column layout at tablet size
- [x] See that there is no hacky DOM duplication or js resize events required
- [x] Weep over the beauty of it (optional)

## Relevant Screenshots/GIFs

Before
screen shot 2017-09-27 at 2 03 58 pm

After
screen shot 2017-09-27 at 2 04 16 pm

## Remaining Tasks

None

## Additional Notes

No

### CODE REVIEW

**Comment by rpama** [comment]
@chelsiejohnston I believe I've addressed all of this now. Was fairly conservative about padding adjustments since I think there are limits to what we can do here given the space and layout, but I agree with the issues you called out and have tried to make it look a little bit better.

**Comment by chelsiejohnston** [comment]
@rpama Thanks! This is much better, that abyss was starting to get pretty full of souls...

Unfortunately all our space is still belongs to that stick figure guy at around the 890px mark:



After this is fixed, I think this will be good to go 👍

**Comment by rpama** [comment]
So my clever reduce the breakpoint by 1 trick doesn't work when the breakpoint variables are in rems not pixels. Now this uses pixels which isn't great, but didn't seem a better way to prevent the col-6 styles from triggering while the floats were also still triggered. Thanks for catching the return of the greedy screen hogging stick man @chelsiejohnston.

**Comment by chelsiejohnston** [comment]
I created https://issues.ama-assn.org/browse/EWL-4009 to cover the d8 implementation of this work.

**Comment by chelsiejohnston** [comment]
@rpama LGTM, please resolve merge conflicts and then this can go in! Thanks!

**Pull request merged**
