### PR TITLE
Ewl 3528 create documentation

### PR DESCRIPTION
**Pull request by rpama**
## JIRA Ticket(s)
- [EWL-3528: Create Documentation about standards for style guide contributors](https://issues.ama-assn.org/browse/EWL-3528)

## Description:
Per discussion with @froboy and @chelsiejohnston, creates a docs folder for more comprehensive documentation for working with the style guide as a code contributor. Moves some documentation out of the index file and into it's own markdown file in that new docs folder.

## To Test:
- [ ] Read the updated index
- [ ] Read the files in the docs folder

## Automated Test:
N/A

## Relevant Screenshots/GIFs:
N/A

## Remaining Tasks:
Adding documentation will be an ongoing process. Notably absent is documentation for people _using_ the style guide rather than code contributors.

## Additional Notes:
No.

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

### CODE REVIEW

**Comment by froboy** [comment]
@rpama it looks like a lot of this conflicts with the changes in #122. Could you please resolve the merge conflicts?

**Comment by rpama** [comment]
@chelsiejohnston made updates to that which is why ideally she was reviewing this to make sure her updates didn't get lost, @froboy.

**Comment by froboy** [comment]
@rpama I changed the assignment accordingly.

**Comment by chelsiejohnston** [comment]
Merging hoorayyyyyy bitmoji

**Pull request merged**
