### PR TITLE
EWL-3108 style guide view takeover interactions

### PR DESCRIPTION
**Pull request by chelsiejohnston**
## JIRA Ticket(s)
- [EWL-3108: style guide view takeover interactions](https://issues.ama-assn.org/browse/EWL-3108)

## Description:
Animates the collapsing of the primary nav from its open state, both on mobile and at larger breakpoints.

## To Test:
- [x] Navigate to ~Pages~ Templates > Home > Home
- [x] View the page at a mobile breakpoint; interact with the "Menu" and observe its collapse animation
- [ ] View the page at a desktop breakpoint; interact with the "Menu" and observe its collapse animation

## Automated Test:
N/A

## Remaining Tasks:
N/A

## Additional Notes:
Should be merged after https://github.com/AmericanMedicalAssociation/AMA-style-guide/pull/126 - was branched from the branch in that PR.

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

### CODE REVIEW

**Comment by chelsiejohnston** [comment]
@rpama I think I've addressed everything from the last comment. When you get a chance, please re-review and we can finally close this out (I hope) :)

**Comment by rpama** [comment]
This is definitely in better shape than before and several of the previous issues have been fixed (woot!). I'm still seeing two issues though which I think we need to address:
- [ ] When you first load the page, the menu shows expanded and then immediately closes. It should ideally start as closed and never fire the closing animation
- [ ] The menu isn't scrollable on mobile, so users cannot get to all the possible options on long menus. (See below)

primary_nav_mobile_no_scrolling

**Comment by chelsiejohnston** [comment]
>  When you first load the page, the menu shows expanded and then immediately closes. It should ideally start as closed and never fire the closing animation
After some time trying to reproduce this I'm not totally sure that it's the menu closing that's causing this visual effect. It seems like some other FOUC happening.

@rpama I may need help troubleshooting this one.

**Comment by froboy** [comment]
As per FED meeting 9/26/2017 closing this PR until we have a need for it, at which point we'll try again from scratch.

**Pull request closed without merging**
