### PR TITLE
Ewl 3093 css tab patch

### PR DESCRIPTION
**Pull request by rpama**
## Ticket(s)
**Jira Ticket**

- [EWL-3093: Get CSS in Tab](https://issues.ama-assn.org/browse/EWL-3093)

Related PR:
- [https://github.com/AmericanMedicalAssociation/AMA-style-guide/pull/144](https://github.com/AmericanMedicalAssociation/AMA-style-guide/pull/144)

## Description

Uses patches instead of gulp to achieve scss panel injection.

## To Test

- [ ] You should probably delete your current `vendor/pattern-lab` folder so that it will force reinstallation and guarantee the patches are applied
- [ ] Navigate to `styleguide/` and run `composer install`
- [ ] run `gulp serve` or `./node_modules/.bin/gulp serve`
- [ ] Click upper right Settings gear > Show Pattern Info
- [ ] See that scss panel exists
- [ ] Go to a pattern with scss (so not the intro) and see that the scss is available in the pattern

## Relevant Screenshots/GIFs

screen shot 2017-06-16 at 10 53 08 am

## Remaining Tasks

There are countless improvements that could be made, but probably separate tickets should be made for those

## Additional Notes

This is a somewhat nicer approach than the gulp, but composer is less predictable about when it recognizes patch updates when you run `composer install`. You sometimes have to purge the libraries to force it to install and patch.

**PR #144 should be closed out if/when this is merged.**

### CODE REVIEW

**Comment by rpama** [comment]
I'm wondering if there's still some gulp fixes from PR #144 that need to go into this. It's working on my end, but not sure if it will work for everyone.

**Comment by froboy** [comment]
@rpama `composer install --prefer-source` will force a re-download without blowing away the entire vendor folder.

**Comment by froboy** [comment]
@rpama this is looking great. The only thing I'd potentially consider for MVP is only showing the tab on patterns for which SCSS exists. Do you think this is possible or should it go in another ticket?

**Comment by rpama** [comment]
@froboy I had made a quick attempt to see if I could hide that panel when there's no scss through the PHP side and I kinda broke it. I'll take a quick stab at trying to suppress it on the js side and see how that works out. If I can get that working relatively quickly, I'll try to roll it in to this PR.

**Comment by rpama** [comment]
@froboy I'm not sure that turning off the scss tab on a per-pattern basis is possible, since the Panel.add() is only ever called once. There might be a way to put some placeholder data in the scss tab if there is none so that it doesn't look blank (something like, 'sorry, we don't have any css for this pattern') but we should probably open a separate ticket for that.

**Comment by rpama** [comment]
Seems it's actually pretty easy to put the "no scss available" message so I'm going to do that for this PR.

**Comment by froboy** [comment]
I had to `rm -rf vendor/*` to get this to work this time.. not sure why. I'll take it though.

**Comment by rpama** [comment]
@froboy as noted in the PR "composer is less predictable about when it recognizes patch updates when you run `composer install`. You sometimes have to purge the libraries to force it to install and patch."

**Pull request merged**
