### PR TITLE
EWL - 3112 animate audience selector

### PR DESCRIPTION
**Pull request by martensc**
Ticket: https://issues.ama-assn.org/browse/EWL-3112

To test:
- Go to Organisms > Sections > Audience Selector
- If the viewport is less than 900px wide, the Audience Selector should collapse. You should be able to click on the dropdown and the list will slide animate to open. Clicking the list again will slide close.
- If the viewport is more than 900px wide, the Audience Selector should be visible and display inline.

### CODE REVIEW

**Comment by martensc** [comment]
@aCyborg good question. @froboy is this correct? See Ashley's comment.

**Comment by froboy** [comment]
@martensc @aCyborg correct. The scope of this ticket is just animating the dropdown and the add more. The audience selector is not fully implemented.

**Comment by aCyborg** [comment]
@martensc I tried to resolve the merge conflicts, but it looks like something may have broken. The dropdown no longer works for me at mobile. I'm not going to push my merge (though I don't think thats what did it), and I'll leave it to you to take a look at tomorrow.

**Comment by labbydev** [comment]
@martensc I had similar issues but it's not the merge conflicts that's preventing it from opening. There is a fixed height on the `ul`, so while the js is working to expand it correctly the fixed height is preventing it from actually opening.

**Comment by labbydev** [comment]
@aCyborg @martensc the merge conflict caused the problem, but I was able to fix both quickly. This is good to go. Merging.

**Pull request merged**
