### PR TITLE
Ewl 3082 store js with components

### PR DESCRIPTION
**Pull request by rpama**
## JIRA Ticket(s)
- [EWL-3082](https://issues.ama-assn.org/browse/EWL-3082)
- related to [EWL-3487](https://issues.ama-assn.org/browse/EWL-3487)

## Description:
- Makes gulp concat the js into one app.js file and references that in the foot.twig file instead of calling each out individually
- Makes gulp concat jquery and jquery.validation first so that dependencies resolve correctly
- Tells gulp to look in the _patterns folders for js files so we can store pattern-specific js with the relevant component
- Moves component specific-js to the appropriate pattern folder
- Wraps the primary-nav and jump-nav js in a check to make sure those elements exist so we stop getting a million js errors in the console (that probably should not have gone in this PR, but I accidentally committed it)

## To Test:
- In console/network tab, you can see the new app.js file gets pulled in

## Automated Test:
N/A

## Relevant Screenshots/GIFs:
N/A

## Remaining Tasks:
none?

## Additional Notes:
Changes here depend on gulp reconfiguration in PR #115 

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

### CODE REVIEW

**Comment by chelsiejohnston** [comment]
After a quick convo with @rpama, we decided that merging this isn't as straightforward as we'd hoped. Rachel to think on how best to proceed. Leaving this here for now.

**Comment by rpama** [comment]
I've resolved the merge conflicts. I think this is good to go @chelsiejohnston.

**Comment by chelsiejohnston** [comment]
@rpama It is done. Thanks for untangling. :)

**Comment by rpama** [comment]
Woot!

**Pull request merged**
