### PR TITLE
Ewl 3072 styles automation

### PR DESCRIPTION
**Pull request by labbydev**
Ticket: https://issues.ama-assn.org/browse/EWL-3072

## Testing instructions
* `npm install` 
* `gulp serve`
*  change some sass
* Observe autoprefixer runs
* Observe indentation is updated
* `gulp scss-lint`
* Observe there is linting about the quotes, leading zeros, and indentation as well as other items

_does not include linting for Twig, since I was unable to find a way to do that_

### CODE REVIEW

**Comment by froboy** [comment]
@labbydev I can't seem to get linting working...

**Comment by labbydev** [comment]
@froboy I'd love to get another set of eyes on this. I think it's working correctly now, but I'm getting the following error:
```
** postcss-reporter: warnings or errors were found **
Details:
    fileName: /Users/laurenbyrwa/Sites/AMA-style-guide/styleguide/source/assets/css/style.scss
Stack:
Error: 
** postcss-reporter: warnings or errors were found **
    at /Users/laurenbyrwa/Sites/AMA-style-guide/styleguide/node_modules/postcss-reporter/lib/reporter.js:69:13
    at LazyResult.run (/Users/laurenbyrwa/Sites/AMA-style-guide/styleguide/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/Users/laurenbyrwa/Sites/AMA-style-guide/styleguide/node_modules/postcss/lib/lazy-result.js:189:32)
    at /Users/laurenbyrwa/Sites/AMA-style-guide/styleguide/node_modules/postcss/lib/lazy-result.js:194:27
`````
I can't tell if it's coming from the new setup or the styling files

**Comment by labbydev** [comment]
@froboy this should be fixed now.

**Comment by froboy** [comment]
@labbydev @aCyborg @martensc okey doke. This is looking good. I linted all the things, so I'd appreciate someone taking a once-over to the code and style guide to ensure there are no visual regressions.

**Comment by MichellanneLi** [comment]
@froboy When I ran `gulp serve` on this branch, I got the following error message:

Palantirnets-MacBook-Pro:styleguide michellanneli$ gulp serve
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-autoprefixer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michellanneli/Projects/Client Work/AMA-style-guide/styleguide/gulpfile.js:23:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by MichellanneLi** [comment]
@froboy hm. . . . I thought I did, but now I don't remember. Regardless, I ran `npm install` again, then ran `gulp serve`, and it worked great. 

I made changes to the scss and confirmed that it was compiled into css.

I added the following properties to test out the autoprefixer:

- transition -- no autoprefixing
- transform -- no autoprefixing
- column-count -- no autoprefixing
- display: flex -- the autoprefixer added "display: -ms-flexbox."

Not sure in what way indentation should be updated. @froboy could you elaborate?

Where is the linting supposed to occur? I didn't see it in the terminal.

**Comment by froboy** [comment]
@MichellanneLi you have to run the linter manually with `gulp scss-lint` as above.

**Comment by froboy** [comment]
@MichellanneLi it also looks like the indent function doesn't do what Lauren intended. The indent function is goign to need to be replaced with https://www.npmjs.com/package/gulp-lintspaces or something similar. LMK if you're comfortable doing this, otherwise I can assign to someone else.

**Comment by froboy** [comment]
Merging this now so we can stop chasing it.

**Pull request merged**
