### PR TITLE
Prevents jquery conflicts.

### PR DESCRIPTION
**Pull request by deadarm**
Prevents jquery conflicts and addresses errors.

### Steps to test

1. Navigate to ~/www/AMA-style-guide/styleguide
2. Run `composer install`
3. Run `gulp serve`
4. Navigate to home page template
5. Use small viewport
6. Click on Audience Selector and verify it opens and closes
7. Verify there are no errors in console
8. Click on Atoms > View all
9. Verify that you can see all atoms

### CODE REVIEW

**Comment by froboy** [comment]
This fixes some things, but looks like if you click Atoms > All the error still comes up. Looks like it starts in init.js, maybe?

**Comment by froboy** [comment]
Fix as per https://github.com/pattern-lab/patternlab-php-core/pull/102

**Comment by froboy** [comment]
@martensc can you be sure you ran `composer install` and then check to see if you have this commit in your `Builder.php`?

**Comment by martensc** [comment]
@froboy I ran `composer install` initially. Not sure if something went wrong with it though.

I'm not seeing `Builder.php`

**Comment by froboy** [comment]
@martensc check at `styleguide/vendor/pattern-lab/core/src/PatternLab/Builder.php`?

**Comment by martensc** [comment]
@froboy it looks like `Builder.php` is setup correctly. Here is my terminal window when I run `composer install`.
screen shot 2017-02-27 at 11 07 45 am

I see the same console error: `Uncaught TypeError: $ is not a function` when viewing all Atoms.

**Comment by froboy** [comment]
@martensc can you try one more time? This works for reasies now.

**Comment by martensc** [comment]
@froboy it's working great now! No errors.

**Comment by froboy** [comment]
@martensc thanks!!!!!!!

**Pull request merged**
