### PR TITLE
EWL 3265 - Pagination Controls

### PR DESCRIPTION
**Pull request by martensc**
Ticket: https://issues.ama-assn.org/browse/EWL-3265

To test:
- Go to Molecules > Navigation > Pagination Controls
- Ensure that it works at all viewport sizes.

### CODE REVIEW

**Comment by martensc** [comment]
@labbydev I updated the padding so it doesn't break at smaller viewports.

**Comment by labbydev** [comment]
@martensc I'm still seeing the break. It doesn't happen until you get down to `~340px`, but I'm traditionally just testing using the "S" button in pattern lab which does trigger it.

**Comment by martensc** [comment]
@labbydev ok I think I have it now. I wasn't checking at the absolute smallest viewport prior. Should be good now :)

**Comment by froboy** [comment]
@martensc @labbydev thanks for the review and fixes. This looks great!

**Pull request merged**
