### PR TITLE
Ewl 3279 collapsed filter control

### PR DESCRIPTION
**Pull request by aCyborg**
To test check out:

1. Atoms > Icons > Grid
2. Atoms > Icons > List
3. Atoms > Text > Results count
4. Atoms > Text > Results Count total
5. Molecules > Layouts > Two Up heavier left
6. Molecules > Forms > Filter Toggle
7. Molecules > forms > Applied filters
8. Organisms > Sections > Filter Control

### CODE REVIEW

**Comment by megansabina** [comment]
@aCyborg  - should there be any interactivity on the filer toggle?  I think that it is instead covered here: https://issues.ama-assn.org/browse/EWL-3110 but wanted to verify!

**Comment by aCyborg** [comment]
@megansabina yep, the interactivity is covered in a different ticket than this one!

**Comment by froboy** [comment]
pattern_lab_-_organisms-filter-control
- The icons buttons should be square (have equal padding around all sides of the icon)
- If the dropdown is going to allow overlap I think it should behave a little nicer (some sort of separation between the text and arrow, maybe a little gradient or something), otherwise it could just default to "Best Match".

**Comment by froboy** [comment]
@megansabina could you please review my changes above and if things look good go ahead and merge this?

**Comment by aCyborg** [comment]
@froboy @megansabina this one is not complete since when @froboy and I reviewed it the implemented version on the site of this was much different than the design comp version. This represents the design comp version, and should be modified to match the implemented version more.

**Comment by froboy** [comment]
@megansabina yea, it looks like a few things are different on prod. A few i see:
- Filter box is wider on prod
- Grid and List buttons are reordered

I think keeping the (total) and the applied filters is fine for now. @aCyborg were there other things you noticed that I missed?
__american_medical_association_and_pattern_lab_-_organisms-filter-control

**Comment by megansabina** [comment]
@froboy  - this is ready for review again!

**Comment by froboy** [comment]
LGTM.

**Pull request merged**
